stages:
  - build
  - test

build:
  stage: build
  image: maven:3.6.3-openjdk-11
  script:
    - mvn clean install

test:
  stage: test
  image: maven:3.6.3-openjdk-11
  script:
    - mvn test -Dtest=com.example.tasks.TestAPI