stages:
#  - build
  - test
#
#build:
#  stage: build
#  image: maven:latest
#  script:
#    - mvn clean install

test:
  stage: test
  image: python:3.9
  script:
    - python --version
    - python -m pip install selenium
    - python -m pip install pytest
    - python test.py
