# Generated by Selenium IDE
# import msvcrt
# import time
# import selenium.webdriver.common.by
# import os
# import pytest
import selenium
from selenium.webdriver.chrome import webdriver


class Test:
    def setup_method(self, method):
        self.driver = selenium.webdriver.Chrome()

    def teardown_method(self, method):
        self.driver.quit()

    def test(self):
        self.driver.get("https://translate.yandex.ru/?source_lang=en&target_lang=ru")
        self.driver.maximize_window()        
        self.driver.find_element(selenium.webdriver.common.by.By.CSS_SELECTOR, ".verticalMenuNavItem:nth-child(2)").click()       
        self.driver.find_element(selenium.webdriver.common.by.By.CSS_SELECTOR, ".verticalMenuNavItem:nth-child(3)").click()      
        self.driver.find_element(selenium.webdriver.common.by.By.CSS_SELECTOR, ".verticalMenuNavItem:nth-child(4)").click()       
        self.driver.find_element(selenium.webdriver.common.by.By.CSS_SELECTOR, ".verticalMenuNavItem:nth-child(5)").click()       
        self.driver.find_element(selenium.webdriver.common.by.By.CSS_SELECTOR, ".verticalMenuNavItem:nth-child(66)").click()
        