package com.example.tasks;

import org.junit.Test;
import static constants.Constant.Urls.URL_ADMIN;

public class TestHeading extends BasePage.BasePage {

    @Test
    public void Heading() {
        
        get(URL_ADMIN);
        loginPass(driverChrome);
        clickXpath("//li[@id=\'app-\']/a/span[2]");
        findElementCssSelector("h1");
        clickCssSelector("#doc-logotype .name");
        findElementCssSelector("h1");
        clickLinkText("Catalog");
        findElementCssSelector("h1");
        clickCssSelector("#doc-product_groups .name");
        findElementCssSelector("h1");
        clickCssSelector("#doc-option_groups .name");
        findElementCssSelector("h1");
        clickCssSelector("#doc-manufacturers .name");
        findElementCssSelector("h1");
        clickLinkText("Suppliers");
        findElementCssSelector("h1");
        clickLinkText("Delivery Statuses");
        findElementCssSelector("h1");
        clickLinkText("Sold Out Statuses");
        findElementCssSelector("h1");
        clickLinkText("Quantity Units");
        findElementCssSelector("h1");
        clickLinkText("CSV Import/Export");
        findElementCssSelector("h1");
        clickXpath("(//li[@id=\'app-\']/a/span[2])[3]");
        findElementCssSelector("h1");
        clickLinkText("Currencies");
        findElementCssSelector("h1");
        clickLinkText("Customers");
        findElementCssSelector("h1");
        clickCssSelector("#doc-csv .name");
        findElementCssSelector("h1");
        clickLinkText("Newsletter");
        findElementCssSelector("h1");
        clickLinkText("Geo Zones");
        findElementCssSelector("h1");
        clickLinkText("Languages");
        findElementCssSelector("h1");
        clickLinkText("Storage Encoding");
        findElementCssSelector("h1");
        clickLinkText("Modules");
        findElementCssSelector("h1");
        clickLinkText("Customer");
        findElementCssSelector("h1");
        clickLinkText("Shipping");
        findElementCssSelector("h1");
        clickLinkText("Payment");
        findElementCssSelector("h1");
        clickLinkText("Order Total");
        findElementCssSelector("h1");
        clickLinkText("Order Success");
        findElementCssSelector("h1");
        clickLinkText("Order Action");
        findElementCssSelector("h1");
        clickLinkText("Orders");
        clickId("content");
        clickLinkText("Order Statuses");
        findElementCssSelector("h1");
        clickLinkText("Pages");
        findElementCssSelector("h1");
        clickLinkText("Reports");
        findElementCssSelector("h1");
        clickLinkText("Most Sold Products");
        findElementCssSelector("h1");
        clickLinkText("Most Shopping Customers");
        findElementCssSelector("h1");
        clickLinkText("Settings");
        findElementCssSelector("h1");
        clickLinkText("Defaults");
        findElementCssSelector("h1");
        clickLinkText("General");
        findElementCssSelector("h1");
        clickLinkText("Listings");
        findElementCssSelector("h1");
        clickLinkText("Images");
        findElementCssSelector("h1");
        clickLinkText("Checkout");
        findElementCssSelector("h1");
        clickLinkText("Advanced");
        findElementCssSelector("h1");
        clickLinkText("Security");
        findElementCssSelector("h1");
        clickLinkText("Slides");
        findElementCssSelector("h1");
        clickLinkText("Tax");
        findElementCssSelector("h1");
        clickCssSelector("#doc-tax_rates .name");
        findElementCssSelector("h1");
        clickLinkText("Translations");
        findElementCssSelector("h1");
        clickCssSelector("#doc-scan .name");
        findElementCssSelector("h1");
        clickLinkText("CSV Import/Export");
        findElementCssSelector("h1");
        clickLinkText("Users");
        findElementCssSelector("h1");
        clickLinkText("vQmods");
        findElementCssSelector("h1");       
    }
}